CC=gcc
FLAGS=-Wall -Werror -Wextra -std=c11

daytimetcpcli1:
	$(CC) $(FLAGS) daytimetcpcli1.c ../lib/error.c -o daytimetcpcli1.out

daytimetcpsrv:
	$(CC) $(FLAGS) daytimetcpsrv.c ../lib/error.c ../lib/wrap.c -o daytimetcpsrv.out